# Generated by Django 4.0.1 on 2022-01-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('stock', models.IntegerField(default=5)),
                ('price', models.IntegerField(default=50)),
            ],
            options={
                'db_table': 'Bread',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
