# Generated by Django 4.0.1 on 2022-01-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0002_bread_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('stock', models.IntegerField(default=5)),
                ('price', models.IntegerField(default=50)),
            ],
            options={
                'db_table': 'Cheese',
            },
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('stock', models.IntegerField(default=5)),
                ('price', models.IntegerField(default=50)),
            ],
            options={
                'db_table': 'Sauce',
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('stock', models.IntegerField(default=5)),
                ('price', models.IntegerField(default=50)),
            ],
            options={
                'db_table': 'Topping',
            },
        ),
    ]
