# Generated by Django 4.0.1 on 2022-01-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0004_alter_bread_price_alter_bread_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sandwich',
            old_name='Sauce',
            new_name='sauce',
        ),
    ]
