# Generated by Django 4.0.1 on 2022-01-24 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0005_rename_sauce_sandwich_sauce'),
    ]

    operations = [
        migrations.AddField(
            model_name='bread',
            name='existence',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cheese',
            name='existence',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sauce',
            name='existence',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='topping',
            name='existence',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bread',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='cheese',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='bread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_user.bread'),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='cheese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_user.cheese'),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='sauce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_user.sauce'),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='topping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_user.topping'),
        ),
        migrations.AlterField(
            model_name='sauce',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='topping',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
