# Generated by Django 4.0.1 on 2022-01-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0006_bread_existence_cheese_existence_sauce_existence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bread',
            name='existence',
            field=models.BooleanField(),
        ),
    ]
