# Generated by Django 4.0.1 on 2022-01-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0007_alter_bread_existence'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandwich',
            name='existence',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bread',
            name='existence',
            field=models.BooleanField(default=True),
        ),
    ]
