# Generated by Django 4.0.1 on 2022-01-29 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0008_sandwich_existence_alter_bread_existence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('bread', 'bread'), ('topping', 'topping'), ('cheese', 'cheese'), ('sauce', 'sauce')], max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
                ('deleted_data', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Ingredient',
            },
        ),
        migrations.RemoveField(
            model_name='sandwich',
            name='existence',
        ),
        migrations.AddField(
            model_name='sandwich',
            name='deleted_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sandwich',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sandwich',
            name='sauce2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sauce2', to='api_user.ingredient'),
        ),
        migrations.AddField(
            model_name='sandwich',
            name='topping2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topping2', to='api_user.ingredient'),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='bread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bread', to='api_user.ingredient'),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='cheese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheese', to='api_user.ingredient'),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='sauce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sauce', to='api_user.ingredient'),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='topping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping', to='api_user.ingredient'),
        ),
        migrations.DeleteModel(
            name='Bread',
        ),
        migrations.DeleteModel(
            name='Cheese',
        ),
        migrations.DeleteModel(
            name='Sauce',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
    ]
